modLoader="kotlinforforge"
loaderVersion="[1,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "unstuck_alchemy"
version = "${version}"
displayName = "Unstuck Alchemy"
authors = "Mraof"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.unstuck_alchemy]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unstuck_alchemy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unstuck_alchemy]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"
